begin;
create table public.quiz14_editions(id bigint generated by default as identity primary key,title text not null,created_at timestamptz not null default now(),closed_at timestamptz,final_ranking jsonb);
alter table public.quiz14_editions enable row level security;
revoke all on public.quiz14_editions from anon,authenticated;
grant select on public.quiz14_editions to anon,authenticated;
create policy quiz14_editions_read on public.quiz14_editions for select to anon,authenticated using(true);
insert into public.quiz14_editions(id,title) values(1,'Barça-Getafe Quiz');
select setval(pg_get_serial_sequence('public.quiz14_editions','id'),1,true);
alter table public.quiz14_runs add column quiz_id bigint not null default 1 references public.quiz14_editions(id);
alter table public.quiz14_runs drop constraint quiz14_runs_pkey;
alter table public.quiz14_runs add primary key(quiz_id,user_id);
create or replace function public.quiz14_history_leaderboard(p_quiz_id bigint)
returns table(user_id uuid,display_name text,avatar_url text,score integer,finished boolean)
language sql stable security definer set search_path='' as $$
select x.user_id,x.display_name,x.avatar_url,x.score,x.finished from public.quiz14_editions e,
lateral jsonb_to_recordset(e.final_ranking) as x(user_id uuid,display_name text,avatar_url text,score integer,finished boolean)
where e.id=p_quiz_id and e.closed_at is not null
union all
select r.user_id,coalesce(nullif(p.display_name,''),'Culer'),p.avatar_url,r.score,r.finished_at is not null
from public.quiz14_runs r join public.profiles p on p.id=r.user_id join public.quiz14_editions e on e.id=r.quiz_id
where r.quiz_id=p_quiz_id and e.closed_at is null and not coalesce(p.ranking_excluded,false)
order by score desc;
$$;
create or replace function public.quiz14_leaderboard()
returns table(user_id uuid,display_name text,avatar_url text,score integer,finished boolean)
language sql stable security definer set search_path='' as $$
select * from public.quiz14_history_leaderboard((select max(id) from public.quiz14_editions));
$$;
create or replace function public.quiz14_close(p_quiz_id bigint) returns jsonb
language plpgsql security definer set search_path='' as $$
declare e public.quiz14_editions%rowtype; snapshot jsonb;
begin
perform public.vesalaporra_assert_current_admin();
select * into e from public.quiz14_editions where id=p_quiz_id for update;
if not found then raise exception 'Quiz inexistent'; end if;
if e.closed_at is null then
select coalesce(jsonb_agg(to_jsonb(x) order by x.score desc,x.finished_at nulls last,x.started_at,x.user_id),'[]'::jsonb) into snapshot
from (select r.user_id,coalesce(nullif(p.display_name,''),'Culer') display_name,p.avatar_url,r.score,r.finished_at is not null finished,r.finished_at,r.started_at
from public.quiz14_runs r join public.profiles p on p.id=r.user_id where r.quiz_id=e.id and not coalesce(p.ranking_excluded,false)) x;
update public.quiz14_editions set closed_at=clock_timestamp(),final_ranking=snapshot where id=e.id returning * into e;
end if;
return to_jsonb(e)-'final_ranking';
end;
$$;
create or replace function public.quiz14_begin() returns jsonb language plpgsql security definer set search_path='' as $$
declare v public.quiz14_runs%rowtype; uid uuid:=auth.uid();e public.quiz14_editions%rowtype;
begin
if uid is null then raise exception 'Inicia sessió';end if;
select * into e from public.quiz14_editions order by id desc limit 1 for share;
if e.closed_at is not null then raise exception 'Aquest quiz està tancat';end if;
insert into public.quiz14_runs(user_id,quiz_id) values(uid,e.id) on conflict do nothing;
select * into v from public.quiz14_runs where user_id=uid and quiz_id=e.id;
return jsonb_build_object('index',v.question_index,'score',v.score,'deadline',v.question_started_at+interval '10 seconds','finished',v.finished_at is not null);
end $$;
create or replace function public.quiz14_status() returns jsonb language plpgsql security definer set search_path='' as $$
declare v public.quiz14_runs%rowtype; uid uuid:=auth.uid();
begin
if uid is null then raise exception 'Inicia sessió';end if;
select * into v from public.quiz14_runs where user_id=uid and quiz_id=(select max(id) from public.quiz14_editions);
if not found then return null;end if;
return jsonb_build_object('index',v.question_index,'score',v.score,'deadline',v.question_started_at+interval '10 seconds','finished',v.finished_at is not null);
end $$;
create or replace function public.quiz14_submit(p_choice integer) returns jsonb language plpgsql security definer set search_path='' as $$
declare v public.quiz14_runs%rowtype;uid uuid:=auth.uid();e public.quiz14_editions%rowtype;elapsed numeric;awarded int:=0;correct int;nextidx int;done boolean;stamp timestamptz;answers int[]:=array[0,1,0,2,1,2,2,2,0,1,0,0,2,1];
begin
if uid is null then raise exception 'Inicia sessió';end if;
select * into e from public.quiz14_editions order by id desc limit 1 for share;
if e.closed_at is not null then raise exception 'Aquest quiz està tancat';end if;
select * into v from public.quiz14_runs where user_id=uid and quiz_id=e.id for update;
if not found then raise exception 'Comença el Quiz14';end if;
if v.finished_at is not null or v.question_index>=14 then raise exception 'Joc acabat';end if;
correct:=answers[v.question_index+1];stamp:=clock_timestamp();elapsed:=extract(epoch from stamp-v.question_started_at);
if p_choice=correct and elapsed>=0 and elapsed<10 then awarded:=greatest(10,100-10*floor(elapsed)::int);end if;
nextidx:=v.question_index+1;done:=nextidx>=14;
update public.quiz14_runs set score=v.score+awarded,question_index=nextidx,question_started_at=stamp,finished_at=case when done then stamp else null end where user_id=uid and quiz_id=e.id;
return jsonb_build_object('index',nextidx,'score',v.score+awarded,'deadline',stamp+interval '10 seconds','finished',done,'awarded',awarded,'correct',correct);
end $$;
revoke all on function public.quiz14_close(bigint) from public,anon;
grant execute on function public.quiz14_close(bigint) to authenticated;
revoke all on function public.quiz14_history_leaderboard(bigint) from public;
grant execute on function public.quiz14_history_leaderboard(bigint) to anon,authenticated;
notify pgrst,'reload schema';
commit;
