import { useCallback, useEffect, useRef, useState } from "react";
import { supabase } from "../lib/supabaseClient";
import "./Quiz14.css";
const QUESTIONS = [["Quina ciutat va fer famosa Puyal amb el mític gol maradonià de Messi contra el Getafe?",["Ankara","Istanbul","Sofia","Nàpols"]],["En quina competició va marcar Messi aquell gol el 2007?",["Lliga","Copa del Rei","Champions","Supercopa"]],["Quin dorsal portava Messi quan va marcar aquell gol?",["19","30","10","11"]],["En quin estadi es va marcar el gol maradonià?",["Coliseum","Montjuïc","Camp Nou","Miniestadi"]],["Com va acabar el Barça–Getafe del gol maradonià de Messi?",["4–0","5–2","3–1","6–2"]],["Com va acabar la tornada de semifinals de Copa del 2007, al camp del Getafe?",["2–1","3–0","4–0","1–1"]],["Qui va donar la passada a Messi just abans de la seva cursa maradoniana?",["Iniesta","Deco","Xavi","Eto’o"]],["Quin d’aquests exjugadors del Barça NO ha jugat al Getafe?",["Carles Aleñá","Marc Cucurella","Andrés Iniesta","Munir El Haddadi"]],["Segons la classificació històrica publicada pel Getafe, qui és el seu màxim golejador?",["Jorge Molina","Borja Mayoral","Jaime Mata","Ángel Rodríguez"]],["Quantes vegades havia derrotat oficialment el Getafe al Barça abans del partit d’octubre de 2026?",["2","4","7","10"]],["Com va acabar el Barça–Getafe del 21 de setembre de 2025?",["2–0","3–0","4–1","1–1"]],["Qui va marcar en el Barça 3–0 Getafe de setembre de 2025?",["Ferran Torres (2) i Dani Olmo","Lewandowski (2) i Raphinha","Lamine Yamal i Pedri (2)","Raphinha i Ferran Torres (2)"]],["Com va acabar l’últim Barça–Getafe jugat al Camp Nou abans d’octubre de 2026?",["2–0","4–0","1–0","3–1"]],["Qui va marcar l’únic gol en aquell últim Barça–Getafe al Camp Nou (2023)?",["Gavi","Pedri","Lewandowski","Dembélé"]]];
const GAME_LINK = "https://lliga-epoques-prova.boltxevic.chatgpt.site/";
const CLUES = ["«Ankara Messi!»","Semifinal d’anada de la Copa del Rei.","Messi portava el dorsal 19.","Camp Nou, 18 d’abril de 2007.","El Barça va guanyar 5–2.","El Getafe va remuntar amb un 4–0.","Xavi va passar la pilota a Messi.","Iniesta no va jugar al Getafe.","Jorge Molina.","Quatre victòries abans d’octubre de 2026.","El Barça va guanyar 3–0.","Ferran Torres (2), Dani Olmo.","Barça 1–0 Getafe.","Pedri, al minut 35."];
export default function Quiz14({userId,displayName,avatarUrl}) {
 const [phase,setPhase]=useState("ready"),[data,setData]=useState(null),[ranking,setRanking]=useState([]),[remaining,setRemaining]=useState(10),[reveal,setReveal]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const deadlineRef=useRef(0), submitRef=useRef(false), indexRef=useRef(0), phaseRef=useRef("ready");
 const rank=useCallback(async()=>{const {data:r,error:e}=await supabase.rpc("quiz14_leaderboard");if(!e)setRanking(r||[]);},[]);
 useEffect(()=>{rank();const id=setInterval(rank,7000);return()=>clearInterval(id)},[rank]);
 useEffect(()=>{phaseRef.current=phase},[phase]);
 const submit=useCallback(async choice=>{
  if(submitRef.current||phaseRef.current!=="playing")return;
  submitRef.current=true;setBusy(true);
  const oldIndex=indexRef.current;
  const {data:result,error:e}=await supabase.rpc("quiz14_submit",{p_choice:choice});
  setBusy(false);
  if(e){setError("No s’ha pogut enregistrar la resposta. Torna-ho a provar.");submitRef.current=false;return}
  setData(result);setReveal({correct:result.correct,awarded:result.awarded,index:oldIndex});
  await rank();
  if(result.finished){setPhase("finished");phaseRef.current="finished";setReveal(null);}
  else {
   indexRef.current=result.index;
   setTimeout(()=>{setReveal(null);deadlineRef.current=new Date(result.deadline).getTime();submitRef.current=false;},900);
  }
 },[rank]);
 const submitRefFn=useRef(submit);submitRefFn.current=submit;
 useEffect(()=>{if(phase!=="playing"||reveal)return;const tick=()=>{const seconds=Math.max(0,Math.ceil((deadlineRef.current-Date.now())/1000));setRemaining(seconds);if(seconds===0&&!submitRef.current)submitRefFn.current(-1)};tick();const t=setInterval(tick,80);return()=>clearInterval(t)},[phase,reveal,data?.index]);
 async function begin(){if(!userId)return;setBusy(true);setError("");const {data:r,error:e}=await supabase.rpc("quiz14_begin");setBusy(false);if(e){setError(e.message);return}setData(r);indexRef.current=r.index;deadlineRef.current=new Date(r.deadline).getTime();submitRef.current=false;setPhase(r.finished?"finished":"playing");}
 const refresh=()=>rank();
 const rankBlock=<aside className="q14-ranking"><h3>🏆 CLASSIFICACIÓ GLOBAL <small>● EN DIRECTE</small></h3>{ranking.length===0?<p>Encara no hi ha participants. Sigues el primer!</p>:ranking.map((p,i)=><div className={`q14-rank ${p.user_id===userId?"q14-self":""}`} key={p.user_id}><b>{i+1}</b><span className="q14-photo">{p.avatar_url?<img src={p.avatar_url} alt=""/>:"⚽"}</span><span className="q14-player">{p.display_name}{p.user_id===userId?" · TU":""}</span><strong>{p.score}</strong></div>)}<button className="q14-minibutton" onClick={refresh}>↻ Actualitzar</button></aside>;
 return <div className="q14-root"><header className="q14-top"><div><b className="q14-brand">QUIZ<span>14</span> ⚡</b><p>ESPECIAL BARÇA × GETAFE</p></div><a className="q14-clash" href={GAME_LINK} target="_blank" rel="noopener noreferrer">🕹️ Entrar a Clash of Eras ↗</a></header><div className="q14-layout"><main className="q14-main">
 {phase==="ready"&&<section className="q14-card q14-intro"><p className="q14-kicker">EL REPTE BLAUGRANA</p><h1>QUIZ<span>14</span></h1><p>14 preguntes. 10 segons per resposta. Comences amb 100 punts i en perds 10 per segon. Resposta incorrecta o fora de temps: 0 punts.</p>{userId?<><div className="q14-identity">{avatarUrl?<img src={avatarUrl} alt=""/>:"⚽"}<strong>{displayName}</strong><span>Compte de Vesalaporra</span></div><button className="q14-action" disabled={busy} onClick={begin}>{busy?"CARREGANT…":"COMENÇAR EL REPTE →"}</button><p className="q14-note">Una participació per compte. El teu resultat es guardarà al rànquing global.</p></>:<p className="q14-login">🔒 Entra amb el teu compte de Vesalaporra per participar. No cal crear un usuari nou.</p>}</section>}
 {phase==="playing"&&data&&<section className="q14-card"><div className="q14-info"><span>Pregunta {Math.min(data.index+1,14)} / 14</span><span>{displayName}</span></div><div className="q14-metrics"><div><small>PUNTS EN JOC</small><strong>{remaining*10}</strong></div><div className="q14-clock" style={{"--progress":remaining*10+"%"}}>{remaining}</div><div><small>TOTAL</small><strong>{data.score}</strong></div></div><div className="q14-track"><div style={{width:Math.round(data.index/14*100)+"%"}}/></div><h2 className="q14-question">{QUESTIONS[data.index]?.[0]}</h2><div className="q14-choices">{QUESTIONS[data.index]?.[1].map((a,i)=><button className={reveal&&i===reveal.correct?"q14-correct":""} disabled={busy||!!reveal} key={i} onClick={()=>submit(i)}><b>{"ABCD"[i]}</b>{a}</button>)}</div>{reveal&&<p className="q14-feedback">{reveal.awarded>0?"✅ +"+reveal.awarded+" punts!":"⏱️ 0 punts"} · {CLUES[reveal.index]}</p>}</section>}
 {phase==="finished"&&<section className="q14-card q14-finish"><p>REPTE COMPLETAT</p><h1>PUNTUACIÓ FINAL</h1><div className="q14-zoom">{data?.score??0}</div><div className="q14-identity">{avatarUrl?<img src={avatarUrl} alt=""/>:"⚽"}<strong>{displayName}</strong></div><h2>🏆 CLASSIFICACIÓ DEFINITIVA</h2><p>El teu resultat queda guardat i és visible per a tots els participants.</p><button className="q14-action" onClick={()=>window.open("https://twitter.com/intent/tweet?text="+encodeURIComponent("⚽ He fet "+data.score+" punts al QUIZ14 Barça–Getafe! Supera'm! "+window.location.href),"_blank","noopener,noreferrer")}>Compartir a X</button></section>}
 {error&&<p role="alert" className="q14-error">{error}</p>}</main>{rankBlock}</div></div>;
}
